GET http://localhost:8085/user/374
Accept: application/json 

###
GET http://localhost:8085/users
Accept: application/json 

###
DELETE http://localhost:8085/deleteUser
Content-Type: application/json 

{
    "userId" : "384"
}

###
DELETE http://localhost:8085/deleteAll
Content-Type: application/json 

###
POST http://localhost:8085/signup
Content-Type: application/json 

{
    "username" : "JackD28",
    "email" : "s0349740@salemstate.com",
    "password" : "cpclare",
    "tradingType" : 0,
    "income" : 70000
}

###
POST http://localhost:8085/updateUserTradingInfo
Content-Type: application/json 

{
    "userId" : 374,
    "tradingType" : 1
}

###
POST http://localhost:8085/login
Content-Type: application/json 

{
    "username" : "JackD27",
    "password" : "cpclare"
}

###
PUT http://localhost:8085/editUser
Content-Type: application/json 

{

    "userId" : "374",
    "username" : "JackD27",
    "email" : "jdaviskid27@yahoo.com",
    "password" : "cpclare",
    "tradingType" : "0",
    "income" : "80000"
}

###

POST http://localhost:8085/createTransaction
Content-Type: application/json 

{
    "name" : "Groceries",
    "description" : "Food",
    "date" : "2023-02-07",
    "price" : "89.99",
    "category" : "Needs",
    "category2" : "Food",
    "recurring" : 0,
    "userId" : 374
}

###

PUT http://localhost:8085/editTransaction
Content-Type: application/json 

{
    "name" : "Car Loan",
    "description" : "lol",
    "date" : "2023-02-03",
    "price" : 19.99,
    "category" : "Needs",
    "category2" : "Transportation",
    "recurring" : 1,
    "userId" : 374,
    "transactionId" : 544
}

###
GET http://localhost:8085/allTransactions
Accept: application/json 

###
GET http://localhost:8085/transaction/614
Accept: application/json 

###
GET http://localhost:8085/transactionUser/374
Accept: application/json 

###
GET http://localhost:8085/recurringExpenses/374
Accept: application/json 

###
GET http://localhost:8085/getCurrentYearTotals/374
Accept: application/json 


###
DELETE http://localhost:8085/deleteTransaction
Content-Type: application/json 

{
    "transactionId" : 934
}

###
DELETE http://localhost:8085/deleteTransactionUser
Content-Type: application/json 

{
    "userId" : 374
}


###
DELETE http://localhost:8085/deleteAllTransactions
Content-Type: application/json 


###

POST http://localhost:8085/addWatchlistItem
Content-Type: application/json 

{
    "stockTicker" : "aapl",
    "userId" : 374
}

### 
GET http://localhost:8085/watchlistUser/374
Accept: application/json 

###

GET http://localhost:8085/watchlist
Accept: application/json 

###

POST http://localhost:8085/addPortfolioItem
Content-Type: application/json 

{
    "stockTicker" : "AAPL",
    "dateBoughtAt" : "2020-11-07",
    "price" : 90.67,
    "shares" : 10,
    "userId" : 374
}

### 
GET http://localhost:8085/portfolio
Accept: application/json 

### 
GET http://localhost:8085/portfolioUser/374
Accept: application/json 

###
DELETE http://localhost:8085/deleteWatchlistItem
Content-Type: application/json 

{
    "watchlistitem_id" : 274
}

###
DELETE http://localhost:8085/deletePortfolioItem
Content-Type: application/json 

{
    "portfolioitem_id" : 174
}


